### ISSUE TITLE
Deleting a file with the Rest API keeps returning Not Found

### ISSUE THREAD

**Issue by Elijah-trillionz** [github/rest-api-description#1023]
# Schema Inaccuracy

I am not sure if this is the right place, but I keep having a 404 error whenever I try to delete a file using GitHub rest API. I have provided the required parameters i.e _sha_ and _message_, but it keeps returning not found when the file is there. 
I have also tried getting the file with the GET method and with the same URL and it gets the file just fine, but when I try to delete I get a 404.

## Expected

I expect it to either delete the file or give me more info as to which it was not found.

## Reproduction Steps

- Create a file with your personal access token on any repo
- make a delete request to the file with https://api.github.com/repos/Elijah-trillionz/SortCode-Documents/contents/same.txt as [specified in the documentation](https://docs.github.com/en/rest/reference/repos#delete-a-file) with Elijah-trillionz (owner), SortCode-Documents (repo), and same.txt (path of file)
- add the necessary parameters (sha and message)

Thanks in advance

**Comment by ahoglund** [comment]
@Elijah-trillionz - That sounds like a support related question. I'd suggest you reach out to [them](https://support.github.com/features/rest-api) or the [community forum.](https://github.community/)
