### ISSUE TITLE
I just visited Twitter and see the new UI with rounded corners. So your extension seams to be no longer working.

### ISSUE THREAD

**Issue by 2553BAG** [github/rest-api-description#1136]
I just visited Twitter and see the new UI with rounded corners. So your extension seams to be no longer working.

![grafik](https://user-images.githubusercontent.com/8274816/28680750-8cf915ac-72f7-11e7-8e62-449eb8113ccb.png)

__Originally posted by @MagicAndre1981 in https://github.com/dangeredwolf/ClassicTwitterUI/issues/1__

**Comment by timrogers** [comment]
@2553BAG Hi there 👋🏻 I'm afraid that this isn't the right repo for this issue - this repo is for the OpenAPI descriptions of GitHub's API. The original project, `dangeredolf/ClassicTwitterUI` is archived, but you could always try contacting the maintainer.

**Comment by 2553BAG** [comment]
@2553BAG
