### ISSUE TITLE
[Schema Inaccuracy] Create file returns 404 Not Found

### ISSUE THREAD

**Issue by jim-sheldon** [github/rest-api-description#1147]
# Schema Inaccuracy

Sending a PUT to create a new file in a repository results in an 404 Not Found error.

## Expected

The request should result in a new file being created in the specified repository (or a 401 or 403).

## Reproduction Steps

Taken from the documentation [here](https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents).

curl \
  -X PUT \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/OWNER/REPO/contents/PATH \
  -d '{"message":"my commit message","committer":{"name":"Monalisa Octocat","email":"octocat@github.com"},"content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'

replace OWNER and REPO with a repo owner and the name of a (public) repo

**Comment by jim-sheldon** [comment]
I originally came into this problem while using PyGithub ([method here](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L2074)).

**Comment by ahoglund** [comment]
@jim-sheldon - The 404 may be a result of the repo not existing or you not having access to it as well.

Either way, this would be something you should bring up with https://support.github.com, since this isn't an issue with the OpenAPI description.
