### ISSUE TITLE
[Schema Inaccuracy] Add description for all path parameters

### ISSUE THREAD

**Issue by rachmari** [github/rest-api-description#124]
# Schema Inaccuracy

These path parameters are missing descriptions

- repo
- owner
- ref
- check_run_id
- content_reference_id

These were reported by @hmharvey:

- sha
- ref
- path
- name
- team_slug
- discussion_number
- comment_number
- username
- assignee
- archive_format
- issue_number
- milestone_number
- source
- pull_number
- tag

There are also a lot of `id` parameters without descriptions, and while these aren't as big of a concern when generating, would still be nice for completeness:
- gist_id
- thread_id
- team_id
- reaction_id
- card_id
- column_id
- project_id
- check_run_id
- check_suite_id
- app_id
- status_id
- deployment_id
- hook_id
- event_id
- build_id
- comment_id
- release_id
- asset_id

Additionally, there are a few parameters that also show up with descriptions like `name parameter`. It would be great if these descriptions were more descriptive like `The name of x`. These parameters are:

- release_id
- name
- label

And to be fully transparent, this is from a few releases back so sorry if any of these have changed since! A linting rule I'm sure would help ✨

**Comment by skedwards88** [comment]
Related: https://github.com/github/docs-content/issues/3120
