### ISSUE TITLE
[Schema Inaccuracy] Add preview notes to Blocking Users API

### ISSUE THREAD

**Issue by rachmari** [github/rest-api-description#126]
# Schema Inaccuracy

Originally reported by @runleonarun. https://github.com/github/openapi/issues/215

## Expected

The Blocking Users API is under preview, but there are no preview notes showing up on help-docs. We need to test to make sure all endpoints are under preview but I believe they are as our convention used to be to put the note at the top of the page when all endpoints are under preview.

Compare https://developer.github.com/v3/users/blocking/ and https://help.github.com/en/rest/reference/users#blocking-users

**Comment by skedwards88** [comment]
Closed via https://github.com/github/docs-content/issues/5209
