### ISSUE TITLE
[Schema Inaccuracy] `status` and `simple-commit-status` claim `target_url` (and `description`) are required

### ISSUE THREAD

**Issue by xmo-odoo** [github/rest-api-description#1307]
# Schema Inaccuracy
When fetching the combined statuses for a commit, the details are provided through a `statuses` property defined as:
```json
"statuses": {
  "type": "array",
  "items": {
    "$ref": "#/components/schemas/simple-commit-status"
  }
},
```
`simple-commit-status` has all the fields marked as required and
```json
"target_url": {
  "type": "string",
  "format": "uri"
},
```

`status` combines this issue with also claiming the `"description"` is required and non-nullable:
```json
"description": {
  "type": "string"
},
"target_url": {
  "type": "string"
},
```
Both are incorrect, when resp. fetching and creating a status with `description` and `target_url` left out, both fields are `null` in the responses.

## Expected
That the schema matches the observed results.

## Reproduction Steps
- create a status without providing either `description` or `target_url`
- observe that the successful response has `"description": null` and `"target_url": null`
- fetch the combined status for the commint
- observe that the corresponding simple-status has `"description": null` and `"target_url": null`

Related: #698 (the two components are redundant, and `simple-commit-status` is no simpler than `status`)

**Comment by xmo-odoo** [comment]
> 👋🏻 Thanks for flagging this! Could you please tell me what AOPI you're calling when you "fetch the combined status for the commint"?

Combined statuses: https://docs.github.com/en/rest/commits/statuses#get-the-combined-status-for-a-specific-reference
Creating statuses: https://docs.github.com/en/rest/commits/statuses#create-a-commit-status

**Comment by timrogers** [comment]
@xmo-odoo Thanks! I have reported this to the relevant team at GitHub.

**Comment by timrogers** [comment]
Fixed!
