### ISSUE TITLE
[Schema Inaccuracy] server-statistics missing type

### ISSUE THREAD

**Issue by jessfraz** [github/rest-api-description#1354]
`server-statistics` looks like an object and has properties but has no `type: object`

**Comment by timrogers** [comment]
@jessfraz Thanks for reporting this! I've forwarded this issue to the relevant team at GitHub.

**Comment by timrogers** [comment]
@lildude 👋🏻 Would you be able to take a look at this? @erikaxu mentioned that you'd be a good person to ask.

**Comment by lildude** [comment]
@timrogers sure. Can I bit a more context as the OP is a little cryptic to me.

**Comment by lildude** [comment]
I spoke with @timrogers offline and I know what the issue is now.

**Comment by timrogers** [comment]
@jessfraz This is actually an array of objects. This should be fixed soon 😊
