### ISSUE TITLE
[Schema Inaccuracy] Add enum to `diff-entry.status` schema

### ISSUE THREAD

**Issue by NickCrews** [github/rest-api-description#141]
# Schema Inaccuracy

The [`diff-entry` schema](https://github.com/github/rest-api-description/blob/openapi-update-0b99f0cea5421dd2d56fd563cb894d117b70c4508bbf355f4a68339b5ba5a30c/descriptions/api.github.com/api.github.com.json#L59330) contains info on a changed file. The `status` property is defined as type string, but I believe that it should be narrowed to an enum of `["added", "modified", "removed", "renamed"]`

## Reproduction Steps

I don't know for certain what the possible values of `status` are, but [this GitHub Action](https://github.com/jitterbit/get-changed-files/blob/b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42/src/main.ts#L5) narrows the type to these four values. I figured that if there were any additional values they would have been revealed as errors in that action. I can't think of other modifications you could do to a file, anyways.

The possible values aren't documented publicly anywhere I can see, but presumably within GitHub you could find them, since I think that internally is where they would be defined.

**Comment by dinonuggies1** [comment]
Thanks for reporting this @NickCrews, we will dig further into this on our side!

**Comment by NickCrews** [comment]
Looks like this was updated in https://github.com/github/rest-api-description/commit/60729dde1236bb6a055e57e482f07da847057b75#diff-3e753f5dabec19dcf753e7645b0b25fa18cd5c12bbe7f90493ec976348f11a58R49072, thanks @dinonuggies1!
