### ISSUE TITLE
[Schema Inaccuracy] Issues parsing api.github.com.yaml

### ISSUE THREAD

**Issue by MikeRalphson** [github/rest-api-description#15]
# Schema Inaccuracy

Failure to parse `api.github.com.yaml` using node.js `yaml` module.

```
Multi-line single-quoted string needs to be sufficiently indented at line 30137, column 24:
Multi-line single-quoted string needs to be sufficiently indented at line 58993, column 18
```

## Expected

The YAML file parses with a spec. compliant YAML parser.

## Reproduction Steps

```shell
npm i swagger2openapi
boast https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml
```

**Comment by xuorig** [comment]
Thanks a lot @MikeRalphson. This was fixed in https://github.com/github/rest-api-description/releases/tag/v0.0.2
