### ISSUE TITLE
[Schema Inaccuracy] Schemas contain type: array with no items: keyword

### ISSUE THREAD

**Issue by MikeRalphson** [github/rest-api-description#158]
# Schema Inaccuracy

> expected Object { type: 'array' } to have property items
`#/components/schemas/audit-log-event/properties/config` in https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json

This is only the first such occurrence, there appear to be several.

From the [OpenAPI spec.](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#properties)

> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.

## Expected

At a minimum:

```yaml
type: array
items: {}
```

Ideally a type definition or `$ref` for the array contents.

## Reproduction Steps

```shell
boast https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
```

**Comment by gr2m** [comment]
what is `boast`?

**Comment by MikeRalphson** [comment]
It's a frontend to `oas-validator` which is part of [oas-kit](https://github.com/Mermade/oas-kit)
