### ISSUE TITLE
[Schema Inaccuracy] pull-request.head.repo is not required

### ISSUE THREAD

**Issue by jamesmbourne** [github/rest-api-description#161]
# Schema Inaccuracy

If a pull request is created against a fork and the fork deleted, it is possible for `pull-request.head.repo` to be `null`.

![image](https://user-images.githubusercontent.com/594697/104305775-61c10280-54cd-11eb-9d32-342b098dbc75.png)

## Expected

The `pull-request.head.repo` property is non-required

## Reproduction Steps

```bash
$ curl -X GET https://api.github.com/repos/{repo}/{repoName}/pulls/2
```

**Comment by mattpage** [comment]
This is fixed. See https://github.com/github/rest-api-description/issues/424
