### ISSUE TITLE
[Schema Inaccuracy] To improve types for `repos/get-content` responses

### ISSUE THREAD

**Issue by oscard0m** [github/rest-api-description#165]
# Schema Inaccuracy

Responses for `repos/get-content` operation should be more accurate.

## Expected

- The `"type"` property for responses in `repos/get-content` (`content-directory`, `content-file`, `content-symlink`, `content-submodule`) should be defined with its corresponding literal instead of accepting a type `string`.

- `"title"` and `"description"` for `content-submodule` are wrong

```diff
content-directory: {
	title: "Content Directory",
	description: "A list of directory items",
	type: "array",
	items: {
		type: "object",
			properties: {
				type: {
					type: "string"
+					enum: ["dir"] 
			},
...

content-file: {
	title: "Content File",
	description: "Content File",
	type: "object",
	properties: {
		type: {
			type: "string"
+			enum: ["file"]
		},
...

content-symlink: {
	title: "Symlink Content",
	description: "An object describing a symlink",
	type: "object",
	properties: {
		type: {
			type: "string"
+			enum: ["symlink"]
		},
...

content-submodule: {
-	title: "Symlink Content",
+	title: "Submodule Content",
-	description: "An object describing a symlink",
+	description: "An object describing a submodule",
	type: "object",
	properties: {
		type: {
			type: "string"
+			enum: ["submodule"]
		},
...
```

GitHub Docs reference: https://docs.github.com/en/rest/reference/repos#get-repository-content

## Reproduction Steps
Linking this issue from Octokit where this becomes a TypeScript problem: https://github.com/octokit/rest.js/issues/1971#issuecomment-759693838

**Comment by wolfy1339** [comment]
What you are looking for is `enum`, not `type`. You still want to set `type` to string, and use `enum` to restrict it to certain values

**Comment by oscard0m** [comment]
> What you are looking for is `enum`, not `type`. You still want to set `type` to string, and use `enum` to restrict it to certain values

You are totally right. Updated issue diescription

**Comment by gr2m** [comment]
> ```diff
> content-directory: {
> 	title: "Content Directory",
> 	description: "A list of directory items",
> 	type: "array",
> 	items: {
> 		type: "object",
> 			properties: {
> 				type: {
> 					type: "string"
> +					enum: ["dir"] 
> 			},
> ...
> ```

This is not quite right. The array items returned by a directory response can be either a `file`, a `directory`, a `symlink`, or a `submodule`. Maybe there should be two `schema` definitions for directories, one for the response schema which is an array, and one for an array item, which can be an object with `"type":"dir"`. Then we can use `oneOf` for the array items in case of a directory response and reference the 4 schemas for `content-file`, `content-submodule`, `content-symlink` and `content-directory-item` (or whatever you want to call it)

**Comment by MarcCelani-at** [comment]
Are folks still looking at this?

**Comment by wolfy1339** [comment]
Hi, this is still an issue. Would it be possible to get this fixed

**Comment by timrogers** [comment]
I have just created a PR within GitHub to fix this.
