### ISSUE TITLE
Did the search API rate limit change recently?

### ISSUE THREAD

**Issue by erik-whiting** [github/rest-api-description#1774]
Hello. Am I misremembering, or did the search limit used to be 1000 for an authenticated user?

I'm trying to mine data from a bunch of repositories (500 - 1000) but being limited to 30 searches an hour means I am waiting over half a day to build a nominal data set.

I was doing something like this earlier this year and I could've sworn that by authenticating with my gh username and token that I could search up to 1,000 repositories an hour (actually, I thought it was 5,000 but I might be thinking of enterprise users). Am I remembering incorrectly or did this limit change recently?

**Comment by ahoglund** [comment]
Search limits are much lower than the default 5000 per hour, and none of those have changed in recent times.
