### ISSUE TITLE
[Schema Inaccuracy] Repo Pages `https_certificate.domains` entries should be nullable

### ISSUE THREAD

**Issue by bigfootjon** [github/rest-api-description#1900]
# Schema Inaccuracy

For fetching Pages info, `https_certificate.domains` array entries can be null but the schema is not marked as nullable.

## Expected

The schema should be updated to mark this field as nullable.

## Reproduction Steps

$ curl https://api.github.com/repos/ananthakumaran/monky/pages

(I had to make this request with an auth token, omitted for privacy)

This currently returns:

```json
...
"https_certificate": {
    "state": "approved",
    "description": "The certificate has been approved.",
    "domains": [
      null,
      "www.ananthakumaran.in"
    ],
    "expires_at": "2023-01-07"
  },
...
```

**Comment by yoannchaudet** [comment]
I don't think this is still happening.

https://github.com/github/github/blob/f744a193b80e86ea1774c21f5d651891bd604161/app/api/serializer/repositories_dependency.rb#L1240

![Image](https://github.com/user-attachments/assets/d170cc31-bd36-47a9-bc6a-7e6618ecedb4)

**Comment by bigfootjon** [comment]
@yoannchaudet it definitely still reproduces:

The above API call produces this output on my machine. (my environment mangles arrays and converts them to objects with integer keys). Note the domains field:

```
{
  "url": "https://api.github.com/repos/ananthakumaran/monky/pages",
  "status": "built",
  "cname": null,
  "custom_404": false,
  "html_url": "https://ananthakumaran.in/monky/",
  "build_type": "legacy",
  "source": {
    "branch": "gh-pages",
    "path": "/"
  },
  "public": true,
  "protected_domain_state": null,
  "pending_domain_unverified_at": null,
  "https_certificate": {
    "state": "approved",
    "description": "The certificate has been approved.",
    "domains": {
      "0": null,
      "1": "www.ananthakumaran.in"
    },
    "expires_at": "2024-10-01"
  },
  "https_enforced": true
}
```

**Comment by bigfootjon** [comment]
I can confirm this is working now! Thank you!
