### ISSUE TITLE
[Schema Inaccuracy] `author.login` and `committer.login` should be nullable

### ISSUE THREAD

**Issue by bigfootjon** [github/rest-api-description#1981]
# Schema Inaccuracy

I noticed this in the commit comparison API, but it may be in other places. The `login` of the `author` of a commit object should be nullable, but at the following paths it is not:

* `merge_base_commit.[author|committer].login`
* `base_commit.[author|committer].login`
* `commits[number].[author|committer].login`

## Expected

As the author of a commit may not have a known github login this field should be nullable (as it is in other places in the API)

## Reproduction Steps

$ curl -X POST https://api.github.com/repos/pytorch/pytorch/compare/8073b875d1d22cad62342001670fafb519632e4d...a53ef96743b7c6ca9a104df2a4e144b3743ec548

**Comment by vaindil** [comment]
Thanks for the report! I took a look at this today, and these `author`/`committer` properties are completely null if no associated GitHub user is found. Therefore the `login` property should not be nullable--it will only exist if we found a user with a valid login.

Please let us know if you have an example of this working differently and I can take another look!

**Comment by bigfootjon** [comment]
Ah interesting, looks like the API response has changed. Yeah this looks fine!

Sorry for the bogus report
