### ISSUE TITLE
[Schema Inaccuracy] Deployment `environment` field mismatch

### ISSUE THREAD

**Issue by aaronadamsCA** [github/rest-api-description#2019]
# Schema Inaccuracy

There is an `environment` field mismatch between deployments and deployment statuses that I believe is incorrect.

[Create a deployment](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#create-a-deployment):

> **`environment`** string
> 
> Name for the target deployment environment (e.g., `production`, `staging`, `qa`).
> 
> Default: `production`

[Create a deployment status](https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status):

> **`environment`** string
> 
> Name for the target deployment environment, which can be changed when setting a deploy status. For example, `production`, `staging`, or `qa`.
> 
> Can be one of: `production`, `staging`, `qa`

## Expected

These types should be the same. If `environment` is constrained to one of 3 valid values when creating a deployment status, then it seems it should be constrained to the same 3 values when creating a deployment.

**Comment by izuzak** [comment]
Thanks for reporting this -- the docs should be updated now 🙇 🍰
