### ISSUE TITLE
Typo `at lease` instead of `at least`

### ISSUE THREAD

**Issue by Greesb** [github/rest-api-description#2020]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#check_suite

### What part(s) of the article would you like to see updated?

`at lease` to `at least`

### Additional information

I tried making a PR with the required modifications but it seems we are not allowed to make a PR with those modified json files: https://github.com/github/docs/pull/22952/files

**Comment by izuzak** [comment]
Thanks for reporting this -- this should be fixed now 🙇 🍰
