### ISSUE TITLE
GITHUB Rest APIs returns 404 error for /orgs/org/repos even after adding proper token

### ISSUE THREAD

**Issue by mukulramchandani** [github/rest-api-description#2059]
This is really weird. 
Why anyone would throw 404 even if the error is something different. 
The github APIs just dosen't work. 

Here's the code i'm using. exactly as specified in the docs. 
```
    const octokit = new Octokit({
      auth: `<TOKEN>`,
    });

    octokit.request(
      "GET /orgs/{org}/repos{?type,sort,direction,per_page,page}",
      {
        org: "meta",
      }
    );
```

I have generated Personal Access token with all the permissions. Still its not working at all. 

I think the API should be very easily accessible or atleast error messages should be crisp indicating what exactly going wrong in the request. 

giving 404 is super weird. I'm sure it must be wasting lot of time o so many users. Humble request to bring this change for good.

**Comment by mmrobins** [comment]
Lots of APIs return 404 when you don't have permissions to access something so as not to give away the existence of something you shouldn't have access to, including GitHub's API.  

```
% curl -s -o /dev/null -w "%{http_code}" 'https://api.github.com/orgs/supersecretnowaythisorgexistsbutitmightandimscanningforit/repos'

404
```
