### ISSUE TITLE
[Schema Inaccuracy] Operation  'actions/delete-environment-variable' misses Path parameters

### ISSUE THREAD

**Issue by commonism** [github/rest-api-description#2064]
# Schema Inaccuracy

The operations patch, delete of the PathItem  "/repositories/{repository_id}/environments/{environment_name}/variables/{name}" in the description document https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml miss the Path variable environment_name.

## Expected

The path variables are complete for the operations.
It would reduce duplication to have the path variables attached to the path instead of the operation.

## Reproduction Steps

```
python3 -m venv /tmp/ghapi
/tmp/ghapi/bin/pip install git+https://github.com/commonism/aiopenapi3.git#aiopenapi3

/tmp/ghapi/bin/aiopenapi3 -v validate https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.yaml
…
aiopenapi3.errors.OperationParameterValidationError: ('/repositories/{repository_id}/environments/{environment_name}/variables/{name}', 'delete', 'actions/delete-environment-variable', 'Parameter name not found in parameters: environment_name')
```

**Comment by mnahkies** [comment]
Just encountered the same issue - as above it effects both the `delete` and `patch` methods for the `/repositories/{repository_id}/environments/{environment_name}/variables/{name}` operation.

I was about to send a PR until I saw:
> We don't currently accept pull requests that directly modify the description artifacts found in this repository. 

I appreciate that these definitions are _probably_ auto-generated and hence not wanting PR's to fix things - might be nice to think about whether the generator is able to be open sourced, or some other way to be able to solicit fixes like this from the community
