### ISSUE TITLE
[Schema Inaccuracy] nebula blog post has dangling link

### ISSUE THREAD

**Issue by jsoref** [github/rest-api-description#212]
# Schema Inaccuracy

[api.github.com.yaml](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml) has a url for a [blog post](https://developer.github.com/changes/2019-12-03-internal-visibility-changes/) for `nebula` which in turn has a link to [internal](https://github.com/github/docs/blob/main/content/github/creating-cloning-and-archiving-repositories/creating-a-new-repository.md).

Unfortunately, the `blog post` indicates that `internal` should be documented therein, and it is not.

https://github.com/github/docs/issues/3761#issuecomment-782250712

## Expected

Apparently a replacement blog post that matches the current documentation layout?

## Reproduction Steps

1. Visit [api.github.com.yaml](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml)
2. Look for links to [blog post](https://developer.github.com/changes/2019-12-03-internal-visibility-changes/)
3. Open url
4. Read:
    > Customers with an enterprise account using GitHub Enterprise Cloud and GitHub Enterprise Server 2.20+ have access to a third visibility option beyond public and private, called [internal](https://github.com/github/docs/blob/main/content/github/creating-cloning-and-archiving-repositories/creating-a-new-repository.md). 
5. Click [internal](https://github.com/github/docs/blob/main/content/github/creating-cloning-and-archiving-repositories/creating-a-new-repository.md)
6. Look for `internal` in the text -- for fun, pretend you're using a screen reader (i.e. ignore any pictures that might happen to include `internal` in the bitmap content).

**Comment by skedwards88** [comment]
The correct URL to add is: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-repository-visibility#about-internal-repositories

**Comment by gracepark** [comment]
Hi all, just a heads up, this has been merged in and the link has been updated. Thank you!
