### ISSUE TITLE
`gh api` example paths should not have a leading slash

### ISSUE THREAD

**Issue by earthlyreason** [github/rest-api-description#2140]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

This is in any article that uses the cURL/JavaScript/GitHub CLI examples.

Here is what it looks like for me:

![image](https://user-images.githubusercontent.com/29873545/216100390-0858d022-ab8c-44d4-9946-f463a8a3cd47.png)

That request will produce a 404.  Whereas this request works:

```sh
gh api \
  -H "Accept: application/vnd.github+json" \
  repos/OWNER/REPO/actions/artifacts
```

The only difference is in removal of the leading slash.

### What changes are you suggesting?

The examples don't work as written, apparently due to the leading slash before `repos`.  That slash is (correctly) not used in the examples in [the documentation of the `gh api` subcommand](https://cli.github.com/manual/gh_api).

I presume these examples are generated and that a single code change would correct all instances.

**Comment by cmwilson21** [comment]
@earthlyreason Thanks for opening an issue! I've tagged this for review from [github/rest-api-description](https://github.com/github/rest-api-description), so have transferred it there! ✨

**Comment by mmrobins** [comment]
I'm not finding this to be an issue.  `gh api` works for me with and without the slash mentioned.  Here's my output for the top [trending](https://github.com/trending) repo today

```
% gh api \
  -H "Accept: application/vnd.github+json" \
  /repos/acheong08/ChatGPT/actions/artifacts
{
  "total_count": 0,
  "artifacts": []
}
```

```
% gh api \
  -H "Accept: application/vnd.github+json" \
  repos/acheong08/ChatGPT/actions/artifacts
{
  "total_count": 0,
  "artifacts": []
}
```

You might need to update your `gh` version

```
% gh --version
gh version 2.22.1 (2023-01-27)
https://github.com/cli/cli/releases/tag/v2.22.1
```

**Comment by earthlyreason** [comment]
Thanks for looking into this, and sorry about the noise.  I can't reproduce it now either.  🤷🏽
