### ISSUE TITLE
[Schema Inaccuracy] exclude property of Migration model is inaccurate

### ISSUE THREAD

**Issue by baywet** [github/rest-api-description#2246]
# Schema Inaccuracy

The exclude property for the migration model doesn't have a schema, which will be problematic for any client code generator.
This model is used by the /orgs/{org}/migrations endpoint.

## Expected

exclude property for the Migration model to have a schema or to be removed

**Comment by baywet** [comment]
The failing model/component is #/components/schemas/migration
More precisely the exclude property.

```yaml
        exclude:
          type: array
          items: {}
```
This model is being referenced by the following endpoints:
- /orgs/{org}/migrations
- /orgs/{org}/migrations/{migration_id}
- /user/migrations
- /user/migrations/{migration_id}

I hope that helps, let me know if you need anything else.

**Comment by nickfloyd** [comment]
Got it.  Thank you for the clarity.
