### ISSUE TITLE
[Schema Inaccuracy] `merge_url` get doesn't work

### ISSUE THREAD

**Issue by fernandascovino** [github/rest-api-description#233]
# Schema Inaccuracy

I try to request `merges` from the API but apparently it doesn't exists, why does the `pull` object has a `merges_url` value?

## Reproduction Steps

```python
requests.get("https://api.github.com/repos/basedosdados/mais/merges", auth=(username,token)).json()
[Out]: {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest'}
```

**Comment by xuorig** [comment]
@fernandascovino  The `merges` resource does exist, but only supports `POST` to merge two branches.  Let me know if that fixes it!
