### ISSUE TITLE
[Schema Inaccuracy] Description of the `sort` parameter of the "List issue comments for a repository" endpoint partially wrong

### ISSUE THREAD

**Issue by matthieuprat** [github/rest-api-description#2356]
The "[List issue comments for a repository](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#list-issue-comments-for-a-repository)" endpoint has the following description for the `sort` parameter:

> The property to sort the results by. `created` means when the repository was starred. `updated` means when the repository was last pushed to.

It should probably something along the lines of

> The property to sort the results by. `created` means when the comment was created. `updated` means when the comment was last updated.

**Comment by skedwards88** [comment]
Thanks for checking! It does take some time for the changes to propagate to the docs. It looks like the fix is live now. Thanks again for reporting this!

<img width="359" alt="image" src="https://user-images.githubusercontent.com/25328854/228893700-8f3d8664-8430-4a8c-96a0-3bc53bec45f7.png">

**Comment by matthieuprat** [comment]
Cool, thank you confirming!
