### ISSUE TITLE
[Schema Inaccuracy] license / termsOfService urls

### ISSUE THREAD

**Issue by MikeRalphson** [github/rest-api-description#24]
# Schema Inaccuracy

In the `info` section, the `license.url` property is pointing to GitHub's TOS, when it should be a link to a copy of the MIT license itself. There is an `info.termsOfService` property for this purpose.

## Expected

```yaml
openapi: 3.0.3
info:
  version: 0.0.3
  title: GitHub v3 REST API
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT.html
  termsOfService: https://help.github.com/articles/github-terms-of-service/
  contact:
    name: Support
    url: https://support.github.com
```

## Reproduction Steps

n/a

**Comment by xuorig** [comment]
Addressed by https://github.com/github/rest-api-description/commit/c651ddd75c874d3286642d2c9e64c25ddc1f692b & https://github.com/github/rest-api-description/commit/140582ea9c53cf133755788331c37413e1a7ec40

Will be in the next release! Thanks again @MikeRalphson

**Comment by MikeRalphson** [comment]
No, thank you! You deserve a 🏆
