### ISSUE TITLE
[Schema Inaccuracy] Reference to unknown file on line 24456

### ISSUE THREAD

**Issue by WyriHaximus** [github/rest-api-description#2495]
# Schema Inaccuracy

On line `24456` of the `3.1` `api.github.com` `yaml` file there is a reference to a non-existing file in the form of:

```yaml
example: "../../components/examples/deployment_protection_rules.yaml"
```

## Expected

An example matching the structure of the schema instead of a file reference

## Reproduction Steps

Go to https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.yaml and go to line `24456`.

**Comment by izuzak** [comment]
Thanks for reporting this -- this should be fixed now 🙇 🍰
