### ISSUE TITLE
[Schema Inaccuracy] `owner` property in the `full-repository` schema should not be nullable

### ISSUE THREAD

**Issue by wolfy1339** [github/rest-api-description#270]
# Schema Inaccuracy

On the schema, located at `components['schemas']['full-repository']`, the value of `owner` can be `null`. However, a repo has to be owned, so `null` shouldn't be here.

## Expected

`owner` should be only an `object` (`components['schemas']['simple-user']`), not an `object` or `null`

```diff
"full-repository": {
        "title": "Full Repository",
        "description": "Full Repository",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 1296269
          },
...
          "full_name": {
            "type": "string",
            "example": "octocat/Hello-World"
          },
          "owner": {
-           "nullable": true,
            "allOf": [
              {
                "$ref": "#/components/schemas/simple-user"
              }
            ]
          },
          "private": {
            "type": "boolean"
          },
...
    }
```

## Reproduction Steps
```
$ curl -X POST https://api.github.com/repos/{owner}/{repository}
```

This issue manifests itself in downstream consumers of the OpenAPI schema, example, when TypeScript types are generated from this schema in @octokit/openapi-types

/ref octokit/rest.js#2074

**Comment by gr2m** [comment]
@xuorig @imwiss This is blocking https://github.com/octokit/rest.js/issues/37. Could you please look into it?

**Comment by imwiss** [comment]
👋  @wolfy1339 @gr2m we're looking into this, thanks for flagging

**Comment by xuorig** [comment]
This has been fixed!

**Comment by gr2m** [comment]
I created a follow up issue about the referenced `simple-user` schema, which still has `nullable: true`
https://github.com/github/rest-api-description/issues/486
