### ISSUE TITLE
[Schema Inaccuracy] From Docs OS - Fix curl request in rest code samples

### ISSUE THREAD

**Issue by cmwilson21** [github/rest-api-description#2737]
👋 Hey folks, received this in Docs OS repo so am transferring it over here. Let me know if it should be reviewed elsewhere. 

[Original issue here](https://github.com/github/docs/issues/26396)

cc @pietervdheijden 

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All rest articles containing code samples with header X-GitHub-Api-Version. For example:

- https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
- https://docs.github.com/en/rest/repos/autolinks?apiVersion=2022-11-28
- https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Line:

`-H "Authorization: Bearer <YOUR-TOKEN>"\`

Doesn't have a space between `"` and `\`. As a result, the cURL request does not work correctly.

To fix this, the line should be replaced by:

`-H "Authorization: Bearer <YOUR-TOKEN>" \`

### Additional information

![image](https://github.com/github/docs/assets/7749051/a66e32e6-fc74-448f-b65d-67293a8126d9)

**Comment by pietervdheijden** [comment]
@cmwilson21 Thanks for transferring the issue!

I believe this should be the fix: https://github.com/github/docs/pull/26397/files#diff-d8dfbaff0b5edd93db5e5b7b2b72251b164028eaf66382c8f5ec675bed7338a9R85.

**Comment by cmwilson21** [comment]
Another issue mentioning the same missing space from the code - https://github.com/github/docs/issues/26708

**Comment by izuzak** [comment]
This seems to be fixed now, as far as I can tell, so I'll close this out. Thanks again for the report, @pietervdheijden 🙇
