### ISSUE TITLE
[/rest/reference/pulls] "Create a review comment for a pull request" is missing description for `in_reply_to` parameter

### ISSUE THREAD

**Issue by 0xdevalias** [github/rest-api-description#277]
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request--parameters

### What part(s) of the article would you like to see updated?

In the Parameters section, the Description for the `in_reply_to` parameter is currently `undefined`. It would be nice to have a meaningful/user-friendly description here.

### Additional information

![image](https://user-images.githubusercontent.com/753891/113215444-953e4c80-92c6-11eb-9e9a-16c21927ecea.png)

**Comment by skedwards88** [comment]
Thanks for opening this issue! This is now fixed.
