### ISSUE TITLE
[Question] Getting users and repos by legacy databaseId

### ISSUE THREAD

**Issue by SOF3** [github/rest-api-description#28]
Are there any plans to document endpoints starting with `/user/{user_id}` and `/repositories/{repo_id}`?

**Comment by xuorig** [comment]
Hey @SOF3 yes we eventually want to add those endpoints! A lot of paths have aliases of that kind in GitHub's API and we're currently looking at the best way to expose this 👍

**Comment by ahoglund** [comment]
Closing this out as we already have internal tracking for this request.
