### ISSUE TITLE
[Schema Inaccuracy] Incorrect links to webhooks documentation

### ISSUE THREAD

**Issue by nikpivkin** [github/rest-api-description#2908]
# Schema Inaccuracy

The `externalDocs.url` field of the webhooks schema contains incorrect links to documentation.

Example for branch-protection-rule-created webhook:
```yaml
externalDocs:
        url: https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#branch-protection-rule


```

## Expected

The event name is separated by hyphens, but must be separated by underscores.

This is a valid link:
`https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#branch_protection_rule`

**Comment by izuzak** [comment]
Thanks for reporting this -- it should be fixed now! 🍰
