### ISSUE TITLE
[Schema Inefficiency] path parameters are documented at the operation-level instead of the path level

### ISSUE THREAD

**Issue by masklinn** [github/rest-api-description#310]
This is less an inaccuracy and more an inefficiency / complexity: the description generally documents *path* parameters on the operation, meaning if the path has multiple methods / operations, each path parameter will be documented multiple times rather than just once at the path level.

For instance `/gists/{gist_id}` documents the `gist_id` parameter 3 times, on `get`, `patch`, and `delete`.

## Expected

That path parameters be documented just once at the path item level, and possibly overridden in the odd (and unlikely I feel) case that different operations would ascribe different semantics to those paths.

**Comment by xuorig** [comment]
Thanks @masklinn. It's true that its slightly inefficient however our build system works on a per-operation basis. Our current developer experience makes it hard to work with path parameters. Overall the duplication is not a big concern for us at the moment. 🙇
