### ISSUE TITLE
Markdown View for descriptions 

### ISSUE THREAD

**Issue by mayuri2307** [github/rest-api-description#3112]
Hi Team,
First of all, thank you so much for this collation. It is a good repository. Was thinking, if markdown files for the same could also be added for better readability and usability for those who are not familiar with json and yaml files. 
Thanks!

**Comment by bearcherian** [comment]
Thanks for your comment @mayuri2307 . While we don't have plans to add markdown content in this repo, we generate a full documentation page from these API specs which can be viewed at https://docs.github.com
