### ISSUE TITLE
[Schema Inefficiency] Seemingly unnecessary repetition of `enum` values in `GET /issues`

### ISSUE THREAD

**Issue by masklinn** [github/rest-api-description#313]
In the documentation of the `state` and `sort` endpoints of `GET /issues`, the `description` repeats the values documented by the `enum` key, without providing any additional information as to what the values mean.

## Expected

Either for the values not to be repeated (as that generates the risk of the description not matching the `enum` as it evolves), or for additional documentation of the values' semantics to be provided (as with the `filter` parameter, which does duplicate the `enum` values in the `description`, but adds a plain-text description of each value).

**Comment by johscttjr61** [comment]
Now what i do

**Comment by xuorig** [comment]
Thanks for the report @masklinn. That's a good point and I agree with you. However our documentation generator still relies heavily on the description strings. I'll open an issue on our side to track where this is happening and fix this more generally.
