### ISSUE TITLE
[Schema Inaccuracy] GitHub Actions Environment secrets can not be listed in the API if the repo environment name has a slash in it

### ISSUE THREAD

**Issue by scott-doyland-burrows** [github/rest-api-description#3159]
# Schema Inaccuracy

Repo environment secrets can not be listed in the API if the repo environment name has a slash in it.

## Expected

I should be able to list all secrets in an environment no matter what the repo environment name is called.

## Recreate the issue

Create a repo environment named ```a/b``` and then this will show no secrets:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer MY_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repositories/<REPO_ID>/environments/a/b/secrets
```

The same issue occurs if getting an individual secret with:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer MY_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repositories/<REPO_ID>/environments/a/b/secrets/<SECRET_NAME>
```

Documentation link:

https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-environment-secrets

https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#get-an-environment-secret

**Comment by shiftkey** [comment]
:wave: Apologies for the delay @scott-doyland-burrows - I'm reaching out to the team for support as I think this is a bug but I'm not sure how this handles slashes.

**Comment by shiftkey** [comment]
@scott-doyland-burrows the environment names should be URL-encoded - replacing slashes with `%2F` values should do the trick. 

Let me know if that unblocks you and I'll see if we can make this clearer in the docs.

**Comment by scott-doyland-burrows** [comment]
Thanks for the info.  That works fine.
