### ISSUE TITLE
[Schema Inaccuracy] <Missing properties in pulls API endpoint>

### ISSUE THREAD

**Issue by IllyaKh** [github/rest-api-description#3162]
# Schema Inaccuracy

There are some missing fields in `https://api.github.com/repos/[OWNER]/[REPO]/pulls` endpoint. There are no problems with documentation but these fields exist in `https://api.github.com/repos/[OWNER]/[REPO]/pulls/[ID]`

Not implemented fields: 

``` "merged": false,
    "mergeable": false,
    "rebaseable": false,
    "mergeable_state": "dirty",
    "merged_by": null,
    "comments": 4,
    "review_comments": 20,
    "maintainer_can_modify": false,
    "commits": 25,
    "additions": 897,
    "deletions": 11,
    "changed_files": 25
```

## Expected

`https://api.github.com/repos/[OWNER]/[REPO]/pulls` schema matches with the `/repos/[OWNER]/[REPO]/pulls/[ID]` schema

## Reproduction Steps
$ curl -X POST https://api.github.com/repos/[OWNER]/[REPO]/pulls

**Comment by shiftkey** [comment]
@IllyaKh thanks for the feedback!

I believe this [List pull requests](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests) endpoint was implemented to only include a subset of fields that [Get a pull request](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request) supports as this endpoint is required to paginate over open and closed pull requests.

I've passed your feedback onto the team for their consideration but at the moment I believe the schema reflects what is supported by this endpoint.
