### ISSUE TITLE
[Schema Inaccuracy] "/user/tokens/reset": {}

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#328]
# Schema Inaccuracy

There is a new path which doesn't have any methods/operations

```
"/user/tokens/reset": {}
```

## Expected

It shouldn't  be added to the OpenAPI spec unless there are methods? I don't know if this is even valid per specification?

## Reproduction Steps

n/a

**Comment by ahoglund** [comment]
This path should not have been added to the schema as it's not fully GA'ed yet.  I'll look into it.

**Comment by jaslynn674** [comment]
> # Schema Inaccuracy
> There is a new path which doesn't have any methods/operations
> 
> ```
> "/user/tokens/reset": {}
> ```
> 
> ## Expected
> It shouldn't be added to the OpenAPI spec unless there are methods? I don't know if this is even valid per specification?
> 
> ## Reproduction Steps
>Input "Json" #"/user/tokens/reset": {}

**Comment by mattpage** [comment]
This was removed.
