### ISSUE TITLE
[Schema Inaccuracy] Fetching Issues, redirects to Pull Requests instead

### ISSUE THREAD

**Issue by Jonas56** [github/rest-api-description#3506]
# Schema Inaccuracy

When fetching issues for the [rails ](https://github.com/rails/rails/issues) project using the GitHub API, the `html_url` provided in the API response incorrectly redirects to a pull request URL rather than the expected issue URL. 

## Expected

For an issue fetched from the GitHub API, the expected html_url format should directly link to the issue page on GitHub, following the pattern:

```mathematica
Expected URL Format: https://github.com/rails/rails/issues/<issue_id>
```

The actual URL format in the API response is:

```mathematica
Actual URL Redirect: https://github.com/rails/rails/pull/<issue_id>
```

## Reproduction Steps

1. Use the GitHub API to fetch issues related to the Rails project (e.g., curl -X GET https://api.github.com/repos/rails/rails/issues).
2. Inspect the `html_url` field in the API response for any issue.

**Comment by shiftkey** [comment]
@Jonas56 thanks for the feedback! There's [a note in the documentation](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues) that describes more about this historical context:

> Note: GitHub's REST API considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key. Be aware that the id of a pull request returned from "Issues" endpoints will be an issue id. To find out the pull request id, use the "[List pull requests](https://docs.github.com/rest/pulls/pulls#list-pull-requests)" endpoint.

Due to compatibility reasons we've had to keep this behaviour around, but there's extra context in there about how to identify these PRs.

**Comment by Jonas56** [comment]
Thanks for your response.
