### ISSUE TITLE
[Schema Inaccuracy] `"/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}": {}`

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#351]
# Schema Inaccuracy

Similar to #328, there is a new path which doesn't have any methods/operations

```
"/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}": {}
```

@bruce Could you maybe add a linter rule for these? They blow up my tool chain for @octokit automation 🤣

**Comment by mattpage** [comment]
This is now implemented by the reactions `list-for-release` operation
