### ISSUE TITLE
[Schema Inaccuracy] Markdown formatting bug in the listAlertsForRepo code-scanning endpoint

### ISSUE THREAD

**Issue by mario-campos** [github/rest-api-description#3537]
# Schema Inaccuracy

![Image](https://github.com/github/rest-api-description/assets/1663284/18b9147e-b33f-46f0-91cf-744cbb744996)

"closed" is missing a terminating backtick character.

**Comment by skedwards88** [comment]
I don't see this bug in the schema, and I don't have enough information from the screenshot to determine where this is coming from. I'm going to close out this issue, but feel free to open a new issue with more information to help us locate the bug (e.g. if you can link to the GitHub docs where you observe this bug).

**Comment by mario-campos** [comment]
I don't see the bug in GitHub docs. I only see it in the [Octokit docs](https://octokit.github.io/rest.js/v20#code-scanning) (scroll down to _List code scanning alerts for a repository_). And, when [I tried to address it there](https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/735), I was told it was auto-generated and that I should address it here.
