### ISSUE TITLE
@JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.

### ISSUE THREAD

**Issue by jmayes41** [github/rest-api-description#355]
@JakeChampion I think the fix is fine, however I struggle with the test. It runs into the same problem that the response headers are validated. But I can't figure out which package supplies this code. None of the `node_modules` has a `_http_outgoing.js` that I could monkey-patch for this one response to not validate the response headers.

I also can't just test `parseHeaders()` since its private and not globally exported (rightfully so).

So do you have any idea how to test my fix properly?

Fixes #930

__Originally posted by @pke in https://github.com/github/fetch/pull/950__

**Comment by KVROHITH098** [comment]
what is going on here?
