### ISSUE TITLE
[Schema Inaccuracy] Comparison API doesn't list all files in first page, per docs

### ISSUE THREAD

**Issue by kylannjohnson** [github/rest-api-description#3552]
# Schema Inaccuracy
If I summarize https://api.github.com/repos/OWNER/REPO/compare/TAG1...TAG2?page=1&per_page=100 and compare it to its html equivalent, the html page gives 812 file changed with 4889 changes.

As expected, when I implement paging, I get 9 pages, but the first page is incorrect:

Comparison --
Page: total files: 300, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 100
Page: total files: 0, total commits: 6

# Expected
According to the docs for [comparison](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#compare-two-commits), "The list of changed files is only shown on the first page of results, but it includes all changed files for the entire comparison"

# To Reproduce
I just used the paging API per the docs.   I consume the `link` header on each response and, starting with 1, increment the page query parameter as long as `next` returns `true` in the header value

**Comment by stewartlord** [comment]
@github/repos Should we transfer this to your team?

**Comment by kylannjohnson** [comment]
I'm happy to repost to @github/repos if that's more appropriate

**Comment by srt32** [comment]
Thanks! We've got this ask tracked internally now.

**Comment by tamershahin** [comment]
this is still happening to me.. has been fixed or not?

**Comment by Jasonradford51** [comment]
rM3JY6rE595QxiS3zi3Vb4Qyy5sCfuhfcr

**Comment by Jasonradford51** [comment]
Duplicate of #4421
