### ISSUE TITLE
[Schema Inaccuracy] Description regressions

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#36]
# Schema Inaccuracy

the latest update brought back the filler descriptions for parameters, e.g. "secret_name parameter" for the `secret_name` parameter. `github/openapi` did remove these filler descriptions. 

Also for `ref` in `git/list-matching-refs` the description is `ref+ parameter`, but the `{ref+}` URL parameter no longer exists, it's just `{ref}` now. Same with `path+ parameter`, `branch+ parameter`

**actions/delete-self-hosted-runner-from-repo**

-   "scope to use this endpoint." is missing at the end of the operation description

**actions/getself-hosted-runner-for-repo**

-   "endpoint." is missing at the end of the operation description

**repos/create-dispatch-event** (event_type parameter)

-   Description says `event_type` parameter is required, but schema says it's not.

**repos/create-pages-site**

-   Description removed: "The source branch and directory used to publish your Pages site." Just want to make sure this was not a mistake

## Reproduction Steps

n/a

**Comment by zeke** [comment]
cc @github/docs-content @github/ecosystem-api

**Comment by xuorig** [comment]
Fixed in 1.0.0-rc.1!
