### ISSUE TITLE
[Schema Inaccuracy] Promised example not provided in `GET /orgs/{org}/team-sync/groups`

### ISSUE THREAD

**Issue by masklinn** [github/rest-api-description#363]
# Schema Inaccuracy

The description for `GET /orgs/{org}/team-sync/groups` ends brutally after promising an example:

> For example, if the user `octocat` wants to see two groups per page in `octo-org` via cURL, it would look like this:

There is nothing afterwards.

**Comment by skedwards88** [comment]
Thanks for opening this issue! This is now fixed. Since the pagination parameter is common and already mentioned earlier in the description, we deleted this reference to a non-existent example.
