### ISSUE TITLE
[Schema Inaccuracy] Some operations have a category of "code-scanning/

### ISSUE THREAD

**Issue by zeke** [github/rest-api-description#37]
# Schema Inaccuracy

**Comment by xuorig** [comment]
@zeke is this a duplicate of https://github.com/github/rest-api-description/issues/38? I think this is an error but feel free to reopen if that's not the case.

**Comment by zeke** [comment]
Weird. Not sure how this happened. Yep #38 was the only issue I intended to open 👍🏼
