### ISSUE TITLE
[Schema Inaccuracy] `GET /repos/{owner}/{repo}/commits` can respond with 409 if repository is empty

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#385]
# Schema Inaccuracy

the `responses` key for `GET /repos/{owner}/{repo}/commits` is lacking  a `409` key.

Reported by @chalenge in https://github.com/octokit/plugin-paginate-rest.js/issues/158

## Reproduction Steps

```
 ➜ curl -i https://api.github.com/repos/gr2m/empty-repo-for-testing/commits
HTTP/2 409 
server: GitHub.com
# ...

{
  "message": "Git Repository is empty.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-commits"
}
```

**Comment by mattpage** [comment]
@gr2m - the title of this issue says `*/contributors` which would be the `list-contributors` operation but the reproduction steps are for the `list-commits` operation.  Would you mind clarifying?

**Comment by gr2m** [comment]
I mixed up the two endpoints that were mentioned in https://github.com/octokit/plugin-paginate-rest.js/issues/158. I fixed the issue title and description now

**Comment by mattpage** [comment]
`list-commits` currently has a 409 response, so I am going to close this issue. If you feel that the issue was closed by mistake or have more information, feel free to reopen.
