### ISSUE TITLE
[Schema Inaccuracy] Typo in docs

### ISSUE THREAD

**Issue by savage-alex** [github/rest-api-description#42]
# Schema Inaccuracy
Typo whick instead of which on line  26253 of the ghes-2.22.yaml

**Comment by rachmari** [comment]
@savage-alex thanks for letting us know about this! We've got a fix waiting to be merged in #101.

**Comment by shati-patel** [comment]
This was fixed in the linked PR 🎉 Closing...

**Comment by shati-patel** [comment]
(Oops, looks like I don't have enough access to close this 😁)
