### ISSUE TITLE
branch protection's restrictions field description is wrong

### ISSUE THREAD

**Issue by EaseTheWorld** [github/rest-api-description#439]
# Schema Inaccuracy
In  https://docs.github.com/en/rest/reference/repos#update-branch-protection
Properties of the restrictions object is wrong

## Expected
restrictions has users, teams, apps field.
not required_linear_history, allow_force_pushes, allow_deletions....

**Comment by nickfloyd** [comment]
Hey @EaseTheWorld thanks for the feedback on our docs.  Our docs folks have been discussing how to better display nodes that have their own properties.  If you look at the screenshot below you'll notice that there is a `restrictions` definition with a sub-section under it titled `Properties of the `restrictions` object.

That section is followed by the properties (in alphabetical order) that you called out above that are actually peer properties to `restrictions`.  Let me know if that clarifies things or if you were highlighting something else that I might've missed. 

We'd definitely welcome any ideas or feedback that you might have on how we might make this a bit more clear in the docs.

<img width="743" alt="Screen Shot 2021-08-24 at 4 00 25 PM" src="https://user-images.githubusercontent.com/139819/130689194-479f9c94-fe9f-408d-8f68-ae16f5d23f93.png">

**Comment by EaseTheWorld** [comment]
You are right. I didn't know it's expandable.
Thank you.

**Comment by EaseTheWorld** [comment]
Not an issue.
