### ISSUE TITLE
[Schema Inaccuracy] 500 Error founding in API "/user/emails"

### ISSUE THREAD

**Issue by Nana1209** [github/rest-api-description#521]
# Schema Inaccuracy

[`POST https://api.github.com/user/emails`](https://docs.github.com/en/rest/reference/users#add-an-email-address-for-the-authenticated-user) with Authorization and requestBody `{"emails":"xxx@xx.com"}` will cause a 500 error, 
After repeated experiments, 500 errors will be caused when the requestBody is the following structure
`{"emails":"xxx"}`
This is a server error. Incorrectly formatted input was not processed correctly
## Expected

The reponse status should be one of `201,422,304,404,403,401` in `reponses`
## Reproduction Steps

![image](https://user-images.githubusercontent.com/23011465/130196874-e132e417-e575-499f-9d30-0c34ebfae27a.png)

**Comment by gr2m** [comment]
It's not a problem with the schema, but with the API endpoint itself. `emails` is expected to be an array of strings as per [the documentation](https://docs.github.com/en/rest/reference/users#add-an-email-address-for-the-authenticated-user--parameters)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/39992/130266435-8c180788-e007-4b51-bce4-51dd41f9d688.png">

But I agree there shouldn't be a 500 response.

**Comment by Nana1209** [comment]
We are doing some research about REST  API analysis and testing. 
Where should I report  error with github API endpoint itself, like 5XX error?

**Comment by gr2m** [comment]
Best to contact support at https://support.github.com/contact, they will forward your request to the right person.

I'll close the issue as there is nothing actionable regarding the OpenAPI spec
