### ISSUE TITLE
REST API returning 202 and never 200.

### ISSUE THREAD

**Issue by CodyNotFound** [github/rest-api-description#522]
[Github Docs](https://docs.github.com/en/rest/reference/repos)
It seems that the API in the `repos/{owner}/{repo}/stats` directory have been broken
They only returned an empty json like
```
{

}
```

**Comment by CodyNotFound** [comment]
As far as I know, these APIs all return 202:
* [Get the weekly commit activity](https://docs.github.com/en/rest/reference/repos#get-the-weekly-commit-activity)
* [Get the last year of commit activity](https://docs.github.com/en/rest/reference/repos#get-the-last-year-of-commit-activity)
* [Get all contributor commit activity](https://docs.github.com/en/rest/reference/repos#get-all-contributor-commit-activity)
* [Get the weekly commit count](https://docs.github.com/en/rest/reference/repos#get-the-weekly-commit-count)
* [Get the hourly commit count for each day](https://docs.github.com/en/rest/reference/repos#get-the-hourly-commit-count-for-each-day)

**Comment by CodyNotFound** [comment]
See [jstrieb/github-stats #45](https://github.com/jstrieb/github-stats/issues/45) for details

**Comment by CodyNotFound** [comment]
The problem has been solved.
There is something wrong with the Github REST API.

**Comment by jasonk** [comment]
From https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202

> The HyperText Transfer Protocol (HTTP) 202 Accepted response status code indicates that the request has been accepted for processing, but the processing has not been completed;

When you get a 202 status code, it means "I'm collecting the information you asked for, try asking again in a minute to see if it's available yet."
