### ISSUE TITLE
Odd Error When Listing Runner Apps for Org

### ISSUE THREAD

**Issue by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [github/rest-api-description#533]
I realize this repo contains the API description and not the API itself but I did not know where else to report the issue.

[List runner applications for an organization](https://docs.github.com/en/rest/reference/actions#list-runner-applications-for-an-organization) seems pretty straightforward but I'm getting a weird error.

### Steps to reproduce

* (As an organization administrator) create a new access token with the `admin:org` scope
* Authenticate via `curl -i -u YOUR_USERNAME:YOUR_TOKEN https://api.github.com/users/YOUR_USERNAME`
* Run `curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/YOUR_ORG/actions/runners/downloads`

### Error

```
{
  "message": "Must have admin rights to Repository.",
  "documentation_url": "https://docs.github.com/rest/reference/actions#list-runner-applications-for-an-organization"
}
```

This is odd for two reasons:
1. I used a fresh access token with the required scope
2. The request did not target a repository

Am I missing something or is this a bug?

**Comment by mattpage** [comment]
Thank you, I will forward this to the appropriate team.
