### ISSUE TITLE
Unable to create or read branch protection rules using a pattern

### ISSUE THREAD

**Issue by aslakhellesoy** [github/rest-api-description#577]
# Schema Inaccuracy

GitHub allows branch protection rules to specify a branch name pattern. Currently it is only possible to set the pattern via the UI and not via the API.

I am unable to [update a branch protection](https://docs.github.com/en/rest/reference/repos#update-branch-protection) that specifies a *pattern* (such as `release/*`).

I can manually change the branch name to a *pattern* such as `release/*` via GitHub's UI, but after doing that I can no longer read the rule via API.

## Expected

* The schema should specify that the `branch` field can be a literal name *or* a pattern 
* The API should allow updating/creating rules using a pattern, and it should not require that there are existing branches matching that pattern (the UI currently allows this).

## Reproduction Steps

Trying to create a protection rule where the `branch` has the value `release/*`:

```
curl \
  -X PUT \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/{owner}/{repo}/branches/release%2F*/protection \
  -d '{
  "required_status_checks": {
    "strict": true,
    "contexts": []
  },
  "enforce_admins": true,
  "required_pull_request_reviews": null,
  "restrictions": {
    "teams": [],
    "users": []
  }
}'
```

Response:

```
{
  "message": "Branch not found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-branch-protection"
}
```

After changing the name to a pattern in the UI, I get a similar error if I try to read it:

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/{owner}/{repo}/branches/release%2F*/protection
```

Response:

```
{
  "message": "Branch not found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-branch-protection"
}
```

**Comment by aslakhellesoy** [comment]
I've just realised I can use the GraphQL API to create branch protection rules with patterns, so closing this.

**Comment by seilorjr** [comment]
@aslakhellesoy do you have an example using GraphQL API?
