### ISSUE TITLE
[Schema Inaccuracy] `/repos/{owner}/{repo}/git/trees` example simply can not work

### ISSUE THREAD

**Issue by xmo-odoo** [github/rest-api-description#638]
# Schema Inaccuracy

The following request example is provided for the endpoint:
```js
await octokit.request('POST /repos/{owner}/{repo}/git/trees', {
  owner: 'octocat',
  repo: 'hello-world',
  tree: [
    {
      path: 'path',
      mode: 'mode',
      type: 'type',
      sha: 'sha',
      content: 'content'
    }
  ]
})
```
This can not work, the `mode` and `type` don't match any of the expected value, the `sha` is not valid, and the documentation clearly notes that *either* `sha` or `content` must be provided.

**Comment by ahoglund** [comment]
This looks to be a documentation issue, please open an issue on https://github.com/github/docs

**Comment by xmo-odoo** [comment]
@ahoglund I got this example straight from the schema file, and according to the readmes of the repo you link to [they generate the docs from the OpenAPI](https://github.com/github/docs/tree/a3f209fd99235b077fed45ce123e9a0422ed1395/script/rest).
