### ISSUE TITLE
[Schema Inaccuracy] git/update-ref can respond with an undocumented 500 on fairly standard error

### ISSUE THREAD

**Issue by xmo-odoo** [github/rest-api-description#714]
# Schema Inaccuracy

According to the schema, `update-ref` can respond with an HTTP 200 (success) or a 422 (validation failed). However trying to update a ref' to a sha which does not exist in the repository results in a 500, and no payload whatsoever.

## Expected

A 422 with a relevant error message, probably. That is what happens when trying to update a ref with an existing but invalid sha (e.g. updating `refs/heads/xxx` to a tree's sha).

## Reproduction Steps

1. create ref
2. update ref to some nonsense sha, doesn't really matter what as long as it's nowhere near the repository's network

**Comment by ahoglund** [comment]
This isn't so much of an issue with the schema as it is a bug in the implementation (most likely).  This should be filed as such with support https://github.com/support
