### ISSUE TITLE
How to create new branch that is empty using GitHub REST API?

### ISSUE THREAD

**Issue by sandeep-sarkar** [github/rest-api-description#86]
Hi Team,

I want to put new files in my repository `TestRepoSandeep`. This repo has a `master` branch that already contains few files. I want to create a new branch `test` and commit new files there. This new branch should not contain any files from `master`. I am trying to create an empty branch but could not figure out how to do this using GitHub REST API and Python.

Please suggest.

**Comment by gr2m** [comment]
I think a REST API usage question such as this would be best asked at https://github.community/c/github-api-development-and-support/37

**Comment by sandeep-sarkar** [comment]
Posted this question at github community. Closing it here.
