### ISSUE TITLE
[Schema Inaccuracy] incorrect requestBody schema for branch protection endpoints

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#88]
# Schema Inaccuracy

These endpoints now accept a namespaced array in the request body, as documented:

- Add status check contexts (`POST /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts`)
  https://docs.github.com/rest/reference/repos#add-status-check-contexts
- Set status check contexts (`PUT /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts`)
  https://docs.github.com/rest/reference/repos#set-status-check-contexts
- Remove status check contexts (`DELETE /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks/contexts`)
  https://docs.github.com/rest/reference/repos#remove-status-check-contexts
- Add app access restrictions (`POST /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps`)
  https://docs.github.com/rest/reference/repos#add-app-access-restrictions
- Set app access restrictions (`PUT /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps`)
  https://docs.github.com/rest/reference/repos#set-app-access-restrictions
- Remove app access restrictions (`DELETE /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps`)
  https://docs.github.com/rest/reference/repos#remove-app-access-restrictions
- Add team access restrictions (`POST /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams`)
  https://docs.github.com/rest/reference/repos#add-team-access-restrictions
- Set team access restrictions (`PUT /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams`)
  https://docs.github.com/rest/reference/repos#set-team-access-restrictions
- Remove team access restrictions (`DELETE /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams`)
  https://docs.github.com/rest/reference/repos#remove-team-access-restrictions
- Add user access restrictions (`POST /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users`)
  https://docs.github.com/rest/reference/repos#add-user-access-restrictions
- Set user access restrictions (`PUT /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users`)
  https://docs.github.com/rest/reference/repos#set-user-access-restrictions
- Remove user access restrictions (`DELETE /repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users`)
  https://docs.github.com/rest/reference/repos#remove-user-access-restrictions

but the schema for these endpoints is currently defined as 

```json
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "description": "contexts parameter",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
```

## Expected

the schema should instead be an object with a single property, e.g.

```js
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "contexts": {
                    "type": "array",
                    "description": "...",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "example": {
                "labels": [
                  "ci-test",
                  "linter"
                ]
              }
            }
          }
        },
```

## Reproduction Steps

See `curl` examples in the docs linked above

**Comment by imwiss** [comment]
Thanks for reporting this @gr2m.

@xuorig resolved this in https://github.com/github/rest-api-description/pull/99.
