### ISSUE TITLE
Missing enum values on check-run / check-suites properties

### ISSUE THREAD

**Issue by acrobat** [github/rest-api-description#91]
**check-run**
```json
{
          "status": {
            "description": "The phase of the lifecycle that the check is currently in.",
            "example": "queued",
            "type": "string",
            "enum": [
              "queued",
              "in_progress",
              "completed"
            ]
          },
          "conclusion": {
            "type": "string",
            "example": "neutral",
            "nullable": true
          }
}
```

The check run Status has the correct enums defined but the conclusion property is missing a list of possible values. The actual list of possible values is provided in [the documentation](https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#create-a-check-run--parameters)

**Check suites**
```json
{
"status": {
            "type": "string",
            "example": "completed",
            "nullable": true
          },
          "conclusion": {
            "type": "string",
            "example": "neutral",
            "nullable": true
          },
}
```

The same is also the case for the "status" and "conclusion" for check suites

**Comment by rmosolgo** [comment]
This was addressed upstream and the files in this repo have been updated. Thanks for the suggestion!
